all_targets = src

all: $(all_targets) FORCE
clean: $(addprefix clean_,$(all_targets)) FORCE


src: FORCE
	$(CTC_MAKE) -C $(SDK_DIR)/driver/usw/src -f Makefile.vx

clean_src: FORCE
	$(CTC_MAKE) -C $(SDK_DIR)/driver/usw/src -f Makefile.vx  clean

.PHONY: FORCE
FORCE:
